(TeX-add-style-hook
 "luca170201v3-newton_general_relativity"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("fontenc" "T1") ("inputenx" "utf8") ("babel" "main=british") ("csquotes" "autostyle=false" "autopunct=false" "english=british") ("enumitem" "shortlabels" "inline") ("newpxtext" "babel" "theoremfont" "largesc") ("newpxmath" "bigdelims" "nosymbolsc") ("DejaVuSansMono" "scaled=0.84") ("xcolor" "usenames") ("biblatex" "backend=biber" "mcite" "citestyle=authoryear-comp" "bibstyle=pglpm-authoryear" "autopunct=false" "sorting=ny" "sortcites=false" "natbib=false" "maxcitenames=2" "maxbibnames=8" "minbibnames=8" "giveninits=true" "uniquename=false" "uniquelist=false" "maxalphanames=1" "block=space" "hyperref=true" "defernumbers=false" "useprefix=true" "sortupper=false" "language=british" "parentracker=false") ("hyperref" "hypertexnames=false" "pdfencoding=unicode" "psdextra") ("bookmark" "depth=4") ("datetime2" "british")))
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "glyphtounicode"
    "definegreek"
    "fontenc"
    "inputenx"
    "textcomp"
    "amsmath"
    "mathtools"
    "amssymb"
    "amsxtra"
    "babel"
    "csquotes"
    "amsthm"
    "enumitem"
    "newpxtext"
    "newpxmath"
    "DejaVuSansMono"
    "mathdots"
    "xcolor"
    "bm"
    "microtype"
    "biblatex"
    "graphicx"
    "wrapfig"
    "hyperref"
    "bookmark"
    "datetime2")
   (TeX-add-symbols
    '("citebi" ["argument"] 1)
    '("citein" ["argument"] 1)
    '("dd" 1)
    '("widebar" 1)
    '("mynote" 1)
    '("email" 2)
    '("epost" 1)
    '("affiliation" 1)
    '("addparap" 1)
    '("addpara" 1)
    '("addsubsec" 1)
    '("addsec" 1)
    '("addchap" 1)
    '("asudedication" 1)
    '("osfeprint" 1)
    '("biorxiveprint" 1)
    '("doi" 1)
    '("philscieprint" 1)
    '("haleprint" 1)
    '("mparceprint" 1)
    '("arxiveprint" 1)
    '("subtitleproc" 1)
    '("eprint" 2)
    '("href" 2)
    '("mathte" 1)
    '("defquote" 1)
    '("langnohyph" 1)
    "memfontfamily"
    "memfontpack"
    "updated"
    "firstdraft"
    "firstpublished"
    "propertitle"
    "pdftitle"
    "headtitle"
    "pdfauthor"
    "headauthor"
    "reporthead"
    "bmmax"
    "hmmax"
    "QED"
    "sumop"
    "prodop"
    "coprodop"
    "citep"
    "citey"
    "ibid"
    "amp"
    "chapb"
    "urlalt"
    "autanet"
    "addprintnote"
    "atf"
    "de"
    "pu"
    "delt"
    "I"
    "e"
    "di"
    "RR"
    "tr"
    "incr"
    "defd"
    "defs"
    "dotv"
    "con"
    "pf"
    "p"
    "sect"
    "sects"
    "chap"
    "chaps"
    "bref"
    "brefs"
    "eqn"
    "eqns"
    "fig"
    "figs"
    "vs"
    "eg"
    "etc"
    "ie"
    "foll"
    "cf"
    "etal"
    "tprod"
    "tsum"
    "T"
    "puzzle"
    "wrench"
    "psect"
    "psects"
    "dob"
    "dobs"
    "Li"
    "tw"
    "yd"
    "yrr"
    "yr"
    "yrfs"
    "yP"
    "yPc"
    "yEu"
    "yeu"
    "yva"
    "yla"
    "yac"
    "ya"
    "ytn"
    "ycc"
    "yc"
    "yjj"
    "yj"
    "yQ"
    "yqq"
    "yq"
    "yEE"
    "yE"
    "yGG"
    "yG"
    "yEii"
    "yEi"
    "yTT"
    "yT"
    "yTTf"
    "yTf"
    "ybb"
    "yb"
    "ybbf"
    "ybf"
    "ybbi"
    "ybi"
    "ymm"
    "ym"
    "yxxt"
    "yxt"
    "yxxto"
    "yxto"
    "yvvt"
    "yvt"
    "yffg"
    "yfg"
    "yomm"
    "yom"
    "yFF"
    "yF"
    "yFFi"
    "yFi"
    "ycfs"
    "ynn"
    "yn"
    "yvv"
    "yv"
    "yff"
    "yf"
    "ygg"
    "yg"
    "ygv"
    "yKK"
    "yK"
    "yRR"
    "yR"
    "ypp"
    "yp"
    "yeen"
    "ye"
    "yte"
    "ynab"
    "ynaf"
    "yDi"
    "yto"
    "yI"
    "yah"
    "yaw"
    "ybh"
    "ybw"
    "yvh"
    "yvw"
    "yvo"
    "la"
    "shi"
    "tpro"
    "sum"
    "prod"
    "coprod"
    "parentext"
    "bibopenparen"
    "bibcloseparen"
    "finalandcomma"
    "div")
   (LaTeX-add-labels
    "sec:soup"
    "eq:balance_energy_full_gr"
    "eq:dt_momentum"
    "sec:decomp_stress-energy-momentum"
    "eq:decomp_T_cov_3cov"
    "sec:prereqs"
    "sec:frames_relativity"
    "sec:noll_inertia"
    "sec:metric-free"
    "sec:common_kinematics"
    "sec:slicing_frames"
    "eq:observer_field_unit-time"
    "eq:projection_vector"
    "eq:projection_form"
    "eq:wedge_projection"
    "eq:d_projection"
    "eq:contraction_projection"
    "sec:matter"
    "eq:mass_density_closed_three_form"
    "eq:eulerian_frame_conditions"
    "eq:4velocity_explicit"
    "eq:project_matter_form"
    "eq:matter_velocity_in_frame"
    "eq:mass_balance_traditional"
    "sec:newtonian_mechanics_aim"
    "sec:aims_general_rel"
    "sec:search_common_dyn"
    "sec:force_momentum"
    "eq:energy_balance_newtonian"
    "eq:energy_balance_newtonian_combo"
    "eq:div4stress"
    "eq:def4stress_newton"
    "sec:constitutive equations"
    "eq:constitutive_4stress"
    "eq:constit_T_with_mass_geometry"
    "eq:4stress_components"
    "sec:3-1_formulation"
    "eq:decomp_4stress"
    "eq:evolution_eqns"
    "eq:dt_metric"
    "eq:dt_curvat"
    "eq:evolution_eqns2"
    "eq:dt_metric2"
    "eq:dt_curvat2"
    "eq:constraint_eqns"
    "eq:energy_constraint"
    "eq:momentum_constraint"
    "eq:curvature_stretching"
    "eq:mass_balance_gen-rel"
    "eq:constitutive_4stress_gen-rel"
    "eq:constit_energy_gen-rel"
    "eq:constit_energy-flux_gen-rel"
    "eq:constit_3stress_gen-rel"
    "sec:divergence_4stress"
    "eq:evolution_energy_momentum"
    "eq:dt_energy"
    "sec:how_to_solve_3-1"
    "eq:approx_timestepping_dt_metric"
    "item:increase_step"
    "item:increase_step_energy"
    "sec:reinterpretation_metric_temp"
    "eq:evolution_eqns_new"
    "eq:dt_metric_new"
    "eq:dt_curvat_new"
    "eq:constit_mass_new"
    "eq:constit_T_new"
    "sec:geometry_force"
    "sec:force"
    "sec:newton_dynamics_without_absolute_time"
    "sec:decoupling_force_body"
    "sec:interesting_development"
    "eq:stress-matter-momentum"
    "eq:conserv_energy-momentum_try"
    "eq:massb_energyb_relation"
    "eq:why_4stress_zero"
    "eq:div_T_vanishes"
    "sec:altern_newton"
    "sec:newton_dynamics_absolute_time"
    "eq:force_balance_integral"
    "eq:force_balance_ecd_local"
    "sec:really_balance_momentum"
    "eq:conservation_momentum_traditional"
    "eq:conservation_momentum_traditional_integral"
    "eq:conservation_momentum_traditional_differential"
    "eq:fictitious_forces"
    "eq:inertial_force"
    "sec:inertial_force"
    "eq:mass_centre"
    "eq:euler_univ"
    "eq:principal_axes_euler"
    "eq:defin_fixed-star_frame"
    "eq:inertial_force_fixed-stars"
    "sec:energy_balance"
    "eq:balance_energy_traditional"
    "eq:balance_energy_suggests_3form"
    "eq:energy_4velocity"
    "sec:bits"
    "sec:einstein_matter_fields"
    "sec:newtonian_continuum_thermomechanics"
    "sec:newtonian_mechanics_spacetime"
    "eq:no_law_mom_cons"
    "sec:force_balance_newton"
    "eq:gravito-inertial_force_tentative"
    "eq:force_balance"
    "sec:conceptual_problems_stress"
    "sec:summary_newtonian"
    "sec:doubts_remarks")
   (LaTeX-add-environments
    "acknowledgements")
   (LaTeX-add-bibliographies
    "portamanabib")
   (LaTeX-add-mathtools-DeclarePairedDelimiters
    '("abs" "")
    '("set" ""))
   (LaTeX-add-amsthm-newtheorems
    "note"
    "remark"
    "innote")
   (LaTeX-add-amsthm-newtheoremstyles
    "innote")
   (LaTeX-add-enumitem-SetEnumitemKeys
    "para")
   (LaTeX-add-xcolor-definecolors
    "mypurpleblue"
    "myblue"
    "mygreen"
    "myyellow"
    "myred"
    "myredpurple"
    "mygrey"
    "lgrey"
    "shadecolor"
    "mygray"
    "notecolour"))
 :latex)

